import React,{useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ShieldCheck,Lock} from 'lucide-react';
import {authAPI} from '../services/api';

export default function TwoFactorLoginPage(){
 const location=useLocation(), navigate=useNavigate(); const challengeToken=location.state?.challengeToken; const [code,setCode]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 if(!challengeToken) return <div className="min-h-screen flex items-center justify-center p-4"><div className="text-center"><p className="text-gray-600 mb-3">Verification session is missing or expired.</p><button onClick={()=>navigate('/login')} className="text-pink-600 font-semibold">Back to login</button></div></div>;
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{const r=await authAPI.verifyTwoFactorLogin(challengeToken,code);const {token}=r.data.data;localStorage.setItem('token',token);window.location.href='/';}catch(err){setError(err.response?.data?.message||'Invalid authentication code');}finally{setLoading(false)}};
 return <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-pink-200 via-purple-200 to-blue-200 px-4"><div className="bg-white rounded-3xl shadow-2xl p-8 w-full max-w-md"><div className="text-center mb-6"><div className="w-16 h-16 bg-gradient-to-br from-pink-500 to-blue-500 rounded-full flex items-center justify-center mx-auto mb-4"><ShieldCheck className="w-9 h-9 text-white"/></div><h1 className="text-2xl font-bold">Two-factor verification</h1><p className="text-gray-500 mt-2">Enter the 6-digit code from your authenticator, or use a backup code.</p></div>{error&&<div className="bg-red-50 text-red-600 p-3 rounded-lg mb-4 text-sm">{error}</div>}<form onSubmit={submit} className="space-y-4"><div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5"/><input autoFocus value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" required className="w-full pl-10 pr-4 py-3 border rounded-xl text-center tracking-[0.3em]" placeholder="123456"/></div><button disabled={loading||!code} className="w-full py-3 bg-gradient-to-r from-pink-500 to-blue-500 text-white rounded-xl font-semibold disabled:opacity-50">{loading?'Verifying...':'Verify and login'}</button></form><button onClick={()=>navigate('/login')} className="w-full mt-4 text-sm text-gray-500">Cancel</button></div></div>;
}